server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store" always;

    location /js/      { alias /usr/share/nginx/html/src/js/; }
    location /wasm/    { alias /usr/share/nginx/html/src/wasm/; }
    location = /player.css { alias /usr/share/nginx/html/src/player.css; }
}
